trigger: none # Disable push triggers

pr:
    - dev

jobs:
    - job: Build_1P
      displayName: "Build with 1P library"
      pool:
          vmImage: "ubuntu-latest"
      steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
                versionSpec: "16.x"

          - checkout: git://IDDP/msal-javascript-1p
          - script: |
                npm run submodule:init
            displayName: Initialize submodule

          - script: |
                cd ./microsoft-authentication-library-for-js
                git checkout $(System.PullRequest.SourceBranch)
                git pull
            displayName: "Pull latest changes from 3P feature branch"

          - task: npmAuthenticate@0
            displayName: "Authenticate to npm package registry"
            inputs:
                workingFile: ./.npmrc

          - task: npmAuthenticate@0
            displayName: "Authenticate to npm package registry"
            inputs:
                workingFile: ./1ds.npmrc

          - task: Npm@1
            inputs:
                command: "install"
            displayName: "Install Dependencies"

          - task: Npm@1
            inputs:
                command: "custom"
                customCommand: "run build"
            displayName: "Build Msal-Browser-1p"

          - task: Npm@1
            inputs:
                command: "custom"
                customCommand: "run test --workspace=msal-browser-1p"
            displayName: "Test Msal-Browser-1P"
